src/Packagist/WebBundle/Entity/Package.php
<?php

/*
 * This file is part of Packagist.
 *
 * (c) Jordi Boggiano <j.boggiano@seld.be>
 *     Nils Adermann <naderman@naderman.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Packagist\WebBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\ExecutionContext;
use Doctrine\Common\Collections\ArrayCollection;
use Composer\IO\NullIO;
use Composer\Factory;
use Composer\Repository\VcsRepository;
use Composer\Repository\RepositoryManager;

/**
 * @ORM\Entity(repositoryClass="Packagist\WebBundle\Entity\PackageRepository")
 * @ORM\Table(
 *     name="package",
 *     uniqueConstraints={@ORM\UniqueConstraint(name="name_idx", columns={"name"})},
 *     indexes={
 *         @ORM\Index(name="indexed_idx",columns={"indexedAt"}),
 *         @ORM\Index(name="crawled_idx",columns={"crawledAt"}),
 *         @ORM\Index(name="dumped_idx",columns={"dumpedAt"})
 *     }
 * )
 * @Assert\Callback(methods={"isPackageUnique"})
 * @Assert\Callback(methods={"isRepositoryValid"}, groups={"Update", "Default"})
 * @author Jordi Boggiano <j.boggiano@seld.be>
 */
class Package
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * Unique package name
     *
     * @ORM\Column()
     */
    private $name;

    /**
     * @ORM\Column(nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="Packagist\WebBundle\Entity\Version", mappedBy="package")
     */
    private $versions;

    /**
     * @ORM\ManyToMany(targetEntity="User", inversedBy="packages")
     * @ORM\JoinTable(name="maintainers_packages")
     */
    private $maintainers;

    /**
     * @ORM\Column()
     * @Assert\NotBlank(groups={"Update", "Default"})
     */
    private $repository;

    // dist-tags / rel or runtime?

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $crawledAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $indexedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dumpedAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $autoUpdated = false;

    /**
     * @ORM\Column(type="boolean", options={"default"=false})
     */
    private $updateFailureNotified = false;

    private $entityRepository;
    private $router;

    /**
     * @var \Composer\Repository\Vcs\VcsDriverInterface
     */
    private $vcsDriver = true;
    private $vcsDriverError;

    public function __construct()
    {
        $this->versions = new ArrayCollection();
        $this->createdAt = new \DateTime;
    }

    public function toArray()
    {
        $versions = array();
        foreach ($this->getVersions() as $version) {
            /** @var $version Version */
            $versions[$version->getVersion()] = $version->toArray();
        }
        $maintainers = array();
        foreach ($this->getMaintainers() as $maintainer) {
            /** @var $maintainer Maintainer */
            $maintainers[] = $maintainer->toArray();
        }
        $data = array(
            'name' => $this->getName(),
            'description' => $this->getDescription(),
            'time' => $this->getCreatedAt()->format('c'),
            'maintainers' => $maintainers,
            'versions' => $versions,
            'type' => $this->getType(),
            'repository' => $this->getRepository()
        );
        return $data;
    }

    public function isRepositoryValid(ExecutionContext $context)
    {
        // vcs driver was not nulled which means the repository was not set/modified and is still valid
        if (true === $this->vcsDriver && null !== $this->getName()) {
            return;
        }

        $property = 'repository';
        $driver = $this->vcsDriver;
        if (!is_object($driver)) {
            if (preg_match('{https?://.+@}', $this->repository)) {
                $context->addViolationAt($property, 'URLs with user@host are not supported, use a read-only public URL', array(), null);
            } elseif (is_string($this->vcsDriverError)) {
                $context->addViolationAt($property, 'Uncaught Exception: '.$this->vcsDriverError, array(), null);
            } else {
                $context->addViolationAt($property, 'No valid/supported repository was found at the given URL', array(), null);
            }
            return;
        }
        try {
            $information = $driver->getComposerInformation($driver->getRootIdentifier());

            if (false === $information) {
                $context->addViolationAt($property, 'No composer.json was found in the '.$driver->getRootIdentifier().' branch.', array(), null);
                return;
            }

            if (empty($information['name'])) {
                $context->addViolationAt($property, 'The package name was not found in the composer.json, make sure there is a name present.', array(), null);
                return;
            }

            if (!preg_match('{^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*$}i', $information['name'])) {
                $context->addViolationAt($property, 'The package name '.$information['name'].' is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*".', array(), null);
                return;
            }

            if (preg_match('{[A-Z]}', $information['name'])) {
                $suggestName = preg_replace('{(?:([a-z])([A-Z])|([A-Z])([A-Z][a-z]))}', '\\1\\3-\\2\\4', $information['name']);
                $suggestName = strtolower($suggestName);

                $context->addViolationAt($property, 'The package name '.$information['name'].' is invalid, it should not contain uppercase characters. We suggest using '.$suggestName.' instead.');
                return;
            }
        } catch (\Exception $e) {
            $context->addViolationAt($property, 'We had problems parsing your composer.json file, the parser reports: '.$e->getMessage(), array(), null);
        }
        if (null === $this->getName()) {
            $context->addViolationAt($property, 'An unexpected error has made our parser fail to find a package name in your repository, if you think this is incorrect please try again', array(), null);
        }
    }

    public function setEntityRepository($repository)
    {
        $this->entityRepository = $repository;
    }

    public function setRouter($router)
    {
        $this->router = $router;
    }

    public function isPackageUnique(ExecutionContext $context)
    {
        try {
            if ($this->entityRepository->findOneByName($this->name)) {
                $context->addViolationAt('repository', 'A package with the name <a href="'.$this->router->generate('view_package', array('name' => $this->name)).'">'.$this->name.'</a> already exists.', array(), null);
            }
        } catch (\Doctrine\ORM\NoResultException $e) {}
    }

    /**
     * Get id
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Get vendor prefix
     *
     * @return string
     */
    public function getVendor()
    {
        return preg_replace('{/.*$}', '', $this->name);
    }

    /**
     * Get package name without vendor
     *
     * @return string
     */
    public function getPackageName()
    {
        return preg_replace('{^[^/]*/}', '', $this->name);
    }

    /**
     * Set description
     *
     * @param string $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set repository
     *
     * @param string $repository
     */
    public function setRepository($repoUrl)
    {
        $this->vcsDriver = null;

        // prevent local filesystem URLs
        if (preg_match('{^(\.|[a-z]:|/)}i', $repoUrl)) {
            return;
        }

        $this->repository = $repoUrl;

        // avoid user@host URLs
        if (preg_match('{https?://.+@}', $repoUrl)) {
            return;
        }

        try {
            $io = new NullIO();
            $config = Factory::createConfig();
            $io->loadConfiguration($config);
            $repository = new VcsRepository(array('url' => $this->repository), $io, $config);

            $driver = $this->vcsDriver = $repository->getDriver();
            if (!$driver) {
                return;
            }
            $information = $driver->getComposerInformation($driver->getRootIdentifier());
            if (!isset($information['name'])) {
                return;
            }
            if (null === $this->getName()) {

src/Packagist/WebBundle/Resources/views/Web/browse.html.twig
{% extends "PackagistWebBundle:Web:list.html.twig" %}

{% set filters = [] %}

{% if type %}{% set filters = filters|merge(["of type #{type|join(' or ')}"]) %}{% endif %}
{% if tag %}{% set filters = filters|merge(["tagged with #{tag|join(' or ')}"]) %}{% endif %}

{% block content_title %}
    <h1>Packages {{ filters|join(' and ') }}</h1>
{% endblock %}

{# TODO:

- Add browsing by tag, type, most required, ..

#}

src/Packagist/WebBundle/Resources/views/Web/explore.html.twig
{% extends "PackagistWebBundle::layout.html.twig" %}

{% import "PackagistWebBundle::macros.html.twig" as macros %}

{% block content %}
    <div class="box clearfix">
        {% block content_title %}<h1>Packages</h1>{% endblock %}
        {% block lists %}
            <div class="packages-short">
                <h2>New Releases <a href="{{ url('feed_releases', {_format: 'rss'}) }}">RSS</a></h2>
                <ul>
                    {% for version in newlyReleased %}
                        <li><a href="{{ path('view_package', {name: version.name}) }}">{{ version.name }} {{ version.version }}</a> {{ version.description|truncate(40) }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="packages-short">
                <h2>New Packages <a href="{{ url('feed_packages', {_format: 'rss'}) }}">RSS</a></h2>
                <ul>
                    {% for pkg in newlySubmitted %}
                        <li><a href="{{ path('view_package', {name: pkg.name}) }}">{{ pkg.name }}</a> {{ pkg.description|truncate(40) }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="packages-short">
                <h2>Popular Packages</h2>
                <ul>
                    {% for pkg in popular %}
                        <li><a href="{{ path('view_package', {name: pkg.name}) }}">{{ pkg.name }}</a> {{ pkg.description|truncate(40) }}</li>
                    {% endfor %}
                    <li><a href="{{ path('browse_popular') }}">See more...</a></li>
                </ul>
            </div>
            <div class="packages-short">
                <h2>Random Packages</h2>
                <ul>
                    {% for pkg in random %}
                        <li><a href="{{ path('view_package', {name: pkg.name}) }}">{{ pkg.name }}</a> {{ pkg.description|truncate(40) }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endblock %}
    </div>
{% endblock %}

src/Packagist/WebBundle/Resources/views/Web/index.html.twig
{% extends "PackagistWebBundle::layout.html.twig" %}

{% block search %}
    <div class="box">
        <p>Packagist is the main <a href="http://getcomposer.org/">Composer</a> repository. It aggregates all sorts of PHP packages that are installable with Composer.<br /><a href="{{ path('browse') }}">Browse packages</a> or <a href="{{ path('submit') }}">submit your own</a>.</p>
    </div>

    {{ parent() }}
{% endblock %}

{% block content %}
    <div class="box clearfix">
        <section class="getting-started">
            <h1>Getting Started</h1>
            <div>
                <h2>Define Your Dependencies</h2>
                <p>Put a file named <em>composer.json</em> at the root of your project, containing your project dependencies:</p>
                <pre>
{
    "require": {
        "vendor/package": "1.3.2",
        "vendor/package2": "1.*",
        "vendor/package3": ">=2.0.3"
    }
}
</pre>
                <h2>Install Composer In Your Project</h2>
                <p>Run this in your command line:</p>
                <pre>
curl -s http://getcomposer.org/installer | php
</pre>
                <p>Or <a href="http://getcomposer.org/composer.phar">download composer.phar</a> into your project root.</p>
                <h2>Install Dependencies</h2>
                <p>Execute this in your project root.</p>
                <pre>
php composer.phar install
</pre>
                <h2>Autoload Dependencies</h2>
                <p>If all your packages follow the <a href="https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md">PSR-0</a> standard, you can autoload all the dependencies by adding this to your code:</p>
                <pre>
require 'vendor/autoload.php';
</pre>

                <p><a href="{{ path('browse') }}">Browse</a> the packages we have to find more great libraries you can use in your project.</p>
            </div>
        </section>

        <section class="publishing-packages">
            <h1>Publishing Packages</h1>
            <div>
                <h2>Define Your Package</h2>
                <p>Put a file named <em>composer.json</em> at the root of your package, containing this information:</p>
                <pre>
{
    "name": "your-vendor-name/package-name",
    "description": "A short description of what your package does",
    "require": {
        "php": ">=5.3.0",
        "another-vendor/package": "1.*"
    }
}
</pre>
                <p>This is the strictly minimal information you have to give.</p>
                <p>For more details about package naming and the fields you can use to document your package better, see the <a href="{{ path('about') }}">about</a> page.</p>
                <h2>Commit The File</h2>
                <p>You surely don't need help with that.</p>
                <h2>Publish It</h2>
                <p><a href="{{ path('hwi_oauth_connect') }}">Login</a> or <a href="{{ path('fos_user_registration_register') }}">register</a> on this site, then hit the big fat green button above that says <a href="{{ path('submit') }}">submit</a>.</p>
                <p>Once you entered your public repository URL in there, your package will be automatically crawled periodically. You just have to make sure you keep the composer.json file up to date.</p>
            </div>
        </section>
    </div>
{% endblock %}

src/Packagist/WebBundle/Resources/views/Web/list.html.twig
{% extends noLayout|default(false) ? "::base_nolayout.html.twig" : "PackagistWebBundle::layout.html.twig" %}

{% import "PackagistWebBundle::macros.html.twig" as macros %}

{% block content %}
    <div class="box clearfix package-list">
        {% block content_title %}<h1>Packages</h1>{% endblock %}
        {% block list %}
            {% if packages|length %}
                {{ macros.listPackages(packages, paginate is not defined or paginate, false, meta|default(null)) }}
            {% else %}
                <p>No packages found.</p>
            {% endif %}
        {% endblock %}
    </div>
{% endblock %}

src/Packagist/WebBundle/Resources/views/Web/popular.html.twig
{% extends "PackagistWebBundle:Web:list.html.twig" %}

{% block content_title %}<h1>Popular Packages</h1>{% endblock %}

src/Packagist/WebBundle/Resources/views/Web/search.html.twig
{% extends "PackagistWebBundle:Web:list.html.twig" %}

{% block content %}
{% endblock %}

{% block search %}
    <div class="box clearfix">
        {% include "PackagistWebBundle:Web:searchForm.html.twig" %}

        <div class="search-list {% if packages is not defined %}hidden{% endif %}">
            {% if packages is defined %}
                {{ block('list') }}
            {% endif %}
        </div>
    </div>
{% endblock %}

src/Packagist/WebBundle/Resources/views/Web/searchForm.html.twig
<form id="search-form" action="{{ path('search.ajax') }}" method="GET" {{ form_enctype(searchForm) }} autocomplete="off">
    <p class="submit-wrapper"><input class="submit" type="submit" value="Search" /></p>
    <p>
        {{ form_errors(searchForm.query) }}
        {{ form_widget(searchForm.query, {'attr': {'autocomplete': 'off', 'autofocus': 'autofocus', 'placeholder': 'Search packages...', 'tabindex': 1}}) }}
        {{ form_rest(searchForm) }}
    </p>
</form>

src/Packagist/WebBundle/Resources/views/Web/versionDetails.html.twig
{% import "PackagistWebBundle::macros.html.twig" as packagist %}

<p class="requireme">require: <input type="text" readonly="readonly" value="{{ "\"#{version.package.vendor}/#{version.package.packageName}\": \"#{version.hasVersionAlias() ? version.requireVersionAlias : version.requireVersion}\"" }}" /></p>

<h2 class="authors">Author{{ version.authors|length > 1 ? 's' : '' }}</h2>
<ul>
    {% for author in version.authors %}
        <li>
            {%- if author.homepage -%}
                <a href="{{ author.homepage }}">{{ author.name }}</a>
            {%- else -%}
                {{ author.name }}
            {%- endif -%}
            {% if author.email %} &lt;<a href="mailto:{{ author.email }}">{{ author.email }}</a>&gt;{% endif -%}
        </li>
    {% endfor %}
</ul>
<div class="clearfix package-links">
    {% for type in ["require", "devRequire", "suggest", "provide", "conflict", "replace"] %}
        <div class="{{ type }}s">
            <h2>{{ ('link_type.' ~ type)|trans }}</h2>
            {% if attribute(version, type)|length %}
                <ul>
                    {%- for link in attribute(version, type) -%}
                        <li>{{ packagist.packageLink(link.packageName) }}: {{ link.packageVersion == 'self.version' ? version.version : link.packageVersion }}</li>
                    {%- endfor -%}
                </ul>
            {% else %}
                None
            {% endif %}
        </div>
    {% endfor %}
</div>

src/Packagist/WebBundle/Resources/views/Web/viewPackage.html.twig
{% extends "PackagistWebBundle::layout.html.twig" %}

{% block title %}{{ package.name }} - {{ parent() }}{% endblock %}

{% block head_feeds %}
    <link rel="alternate" type="application/rss+xml" title="New Releases - {{ package.name }}" href="{{ url('feed_package', {package: package.name, _format: 'rss'}) }}" />
    <link rel="alternate" type="application/rss+xml" title="New Releases - {{ package.vendor }}" href="{{ url('feed_vendor', {vendor: package.vendor, _format: 'rss'}) }}" />
    {{ parent() }}
{% endblock %}

{% block scripts %}
    <script src="{{ asset('bundles/packagistweb/js/view.js?v=13')}}"></script>
{% endblock %}

{% block content %}
    <div class="box">
        <div class="package"{% if app.user and package.crawledAt is null and (is_granted('ROLE_EDIT_PACKAGES') or package.maintainers.contains(app.user)) %} data-force-crawl="true"{% endif %}>
            {% if is_granted('ROLE_EDIT_PACKAGES') or package.maintainers.contains(app.user) %}
                <form class="action" action="{{ path("edit_package", {name: package.name}) }}">
                    <input type="submit" value="Edit" />
                </form>
            {% endif %}
            {% if is_granted('ROLE_UPDATE_PACKAGES') or package.maintainers.contains(app.user) %}
                <form class="force-update action" action="{{ path('update_package', {name: package.name}) }}" method="POST">
                    <input type="hidden" name="_method" value="PUT" />
                    <input type="hidden" name="update" value="1" />
                    <input type="submit" value="Force Update" />
                </form>
            {% endif %}
            {% if deleteForm is defined %}
                <form class="delete action" action="{{ path('delete_package', {name: package.name}) }}" method="POST">
                    <input type="hidden" name="_method" value="DELETE" />
                    {{ form_widget(deleteForm._token) }}
                    <input type="submit" value="Delete" />
                </form>
            {% endif %}
            <h1>
                {% if is_favorite is defined %}
                    <i class="mark-favorite icon-star{% if not is_favorite %}-empty{% endif %}" data-remove-url="{{ path('user_remove_fav', {name: app.user.username, package: package.name}) }}" data-add-url="{{ path('user_add_fav', {name: app.user.username}) }}" data-package="{{ package.name }}"></i>
                {% endif %}
                <a href="{{ path("view_vendor", {"vendor": package.vendor}) }}">{{ package.vendor }}/</a>{{ package.packageName }}
                <a id="copy" data-clipboard-text="{{ package.name }}" title="Copy to clipboard"><i class="icon-copy"></i></a>
            </h1>
            {% if version and version.tags|length %}
                <p class="tags">
                    {%- for tag in version.tags -%}
                        <a href="{{ url("search", {tags: tag.name}) }}">{{ tag.name }}</a>
                    {%- endfor -%}
                </p>
            {% endif %}

            {% if not package.autoUpdated
                and app.user and (package.maintainers.contains(app.user) or is_granted('ROLE_UPDATE_PACKAGES'))
                and "//github.com/" in package.repository
            %}
                <p class="warning">This package is not auto-updated. Go and set up the <a href="{{ path('fos_user_profile_show') }}">GitHub Service Hook</a> for Packagist so that it gets updated whenever you push!</p>
            {% endif %}

            {% if package.updateFailureNotified
                and app.user and (package.maintainers.contains(app.user) or is_granted('ROLE_UPDATE_PACKAGES'))
            %}
                <p class="warning">This package is in a broken state and will not update anymore. Some branches contain invalid data and until you fix them the entire package is frozen. Click "Force Update" above to see details.</p>
            {% endif %}

            <p class="downloads">
                <span>Overall:</span> {% if downloads.total is defined %}{{ downloads.total|number_format(0, '.', ' ') }} install{{ downloads.total == 1 ? '' : 's' }}{% else %}N/A{% endif %}<br />
                <span>This month:</span> {% if downloads.monthly is defined %}{{ downloads.monthly|number_format(0, '.', ' ') }} install{{ downloads.monthly == 1 ? '' : 's' }}{% else %}N/A{% endif %}<br />
                <span>Today:</span> {% if downloads.daily is defined %}{{ downloads.daily|number_format(0, '.', ' ') }} install{{ downloads.daily == 1 ? '' : 's' }}{% else %}N/A{% endif %}<br />
            </p>

            <p class="description">{{ package.description }}</p>
            <p class="details">
                <span>Maintainer{{ package.maintainers|length > 1 ? 's' : '' }}:</span>
                {% for maintainer in package.maintainers %}
                    <a href="{{ path('user_profile', {'name': maintainer.username}) }}">{{ maintainer.username }}</a>{{ loop.last ? '' : ', ' }}
                {% endfor %}
                {% if addMaintainerForm is defined or removeMaintainerForm is defined %}({% if addMaintainerForm is defined %}<a id="add-maintainer" href="{{ path('add_maintainer', {'name': package.name}) }}">add maintainer</a>{% endif %}{% if addMaintainerForm is defined and removeMaintainerForm is defined %} / {% endif %}{% if removeMaintainerForm is defined %}<a id="remove-maintainer" href="{{ path('remove_maintainer', {'name': package.name}) }}">remove maintainer</a>{% endif %}){% endif %}
                <br />
                {% if version and version.homepage %}
                    <span>Homepage:</span> <a href="{{ version.homepage }}">{{ version.homepage|replace({'http://': ''}) }}</a><br />
                {% endif %}
                {% set repoUrl = package.repository|replace({'git://github.com/': 'https://github.com/', 'git@github.com:': 'https://github.com/'}) %}
                <span>Canonical:</span> <a href="{{ repoUrl }}">{{ repoUrl }}</a><br />
                {% if version.support.source is defined %}
                    <span>Source:</span> <a href="{{ version.support.source }}">{{ version.support.source }}</a><br />
                {% endif %}
                {% if version and version.support.issues is defined %}
                    <span>Issues:</span> <a href="{{ version.support.issues }}">{{ version.support.issues }}</a><br />
                {% endif %}
                {% if version and version.support.irc is defined %}
                    <span>IRC:</span> <a href="{{ version.support.irc }}">{{ version.support.irc }}</a><br />
                {% endif %}
                {% if version and version.support.forum is defined %}
                    <span>Forum:</span> <a href="{{ version.support.forum }}">{{ version.support.forum }}</a><br />
                {% endif %}
                {% if version and version.support.wiki is defined %}
                    <span>Wiki:</span> <a href="{{ version.support.wiki }}">{{ version.support.wiki }}</a><br />
                {% endif %}
            </p>

            {% if addMaintainerForm is defined or removeMaintainerForm is defined %}
                <div>
                    {% if addMaintainerForm is defined %}
                        <form id="add-maintainer-form" class="{{ show_add_maintainer_form|default(false) ? '': 'hidden' }}" action="{{ path('add_maintainer', {'name': package.name}) }}" method="POST" {{ form_enctype(addMaintainerForm) }}>
                            <div>
                                <h2>Add Maintainer</h2>
                                <p>
                                    {{ form_label(addMaintainerForm.user, "Username") }}
                                    {{ form_errors(addMaintainerForm.user) }}
                                    {{ form_widget(addMaintainerForm.user) }}
                                </p>
                                {{ form_rest(addMaintainerForm) }}
                                <input id="submit" type="submit" value="Submit" />
                            </div>
                        </form>
                    {% endif %}

                    {% if removeMaintainerForm is defined %}
                        <form id="remove-maintainer-form" class="{{ show_remove_maintainer_form|default(false) ? '': 'hidden' }}" action="{{ path('remove_maintainer', {'name': package.name}) }}" method="POST" {{ form_enctype(removeMaintainerForm) }}>
                            <div>
                                <h2>Remove Maintainer</h2>
                                <p>
                                    {{ form_label(removeMaintainerForm.user, "Username") }}
                                    {{ form_errors(removeMaintainerForm.user) }}
                                    {{ form_widget(removeMaintainerForm.user) }}
                                </p>
                                {{ form_rest(removeMaintainerForm) }}
                                <input id="submit" type="submit" value="Submit" />
                            </div>
                        </form>
                    {% endif %}
                </div>
            {% endif %}

            {% if package.versions|length %}
                <ul class="versions">
                    {% for version in package.versions %}
                        <li class="version{% if loop.last %} last{% endif %}" id="{{ version.version }}">
                            <section>
                                <h1>
                                    <a href="#{{ version.version }}">
                                        {{- version.version -}}
                                        {% if version.hasVersionAlias() %}
                                            / {{ version.versionAlias }}
                                        {% endif -%}
                                    </a>
                                    {% if version.isDevelopment %}
                                    <span class="source-reference">reference: {{ version.source.reference|prettify_source_reference }}</span>
                                    {% endif %}

                                    {% if deleteVersionCsrfToken is defined %}
                                    <form class="action delete-version" action="{{ path("delete_version", {"versionId": version.id}) }}" method="post">
                                        <input type="hidden" name="_method" value="DELETE" />
                                        <input type="hidden" name="_token" value="{{ deleteVersionCsrfToken }}" />
                                        <input type="submit" value="Delete">
                                    </form>
                                    {% endif %}

                                    <span class="release-date">{{ version.releasedAt|date("Y-m-d H:i") }} UTC</span>
                                    <span class="license{% if not version.license %} unknown{% endif %}">{{ version.license ? version.license|join(', ') : 'Unknown License' }}</span>
                                </h1>

                                <div class="details{% if loop.index0 == 0 %} open{% endif %}">
                                    {% if loop.index0 == 0 %}
                                        {% include 'PackagistWebBundle:Web:versionDetails.html.twig' with {version: version} %}
                                    {% endif %}
                                </div>
                                <div class="details-toggler{% if loop.index0 == 0 %} open{% endif %}"{% if loop.index0 %} data-load-more="{{ path('view_version', {versionId: version.id, _format: 'json'}) }}"{% endif %}></div>
                            </section>
                        </li>
                    {% endfor %}
                </ul>
            {% elseif package.crawledAt is null %}
                <p>This package has not been crawled yet, some information is missing.</p>
            {% else %}
                <p>This package has no released version yet, and little information is available.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

src/Packagist/WebBundle/Resources/views/Web/viewVendor.html.twig
{% extends "PackagistWebBundle:Web:list.html.twig" %}

{% block head_feeds %}
    <link rel="alternate" type="application/rss+xml" title="New Releases - {{ vendor }}" href="{{ url('feed_vendor', {vendor: vendor, _format: 'rss'}) }}" />
    {{ parent() }}
{% endblock %}

{% block content_title %}<h1>Packages from {{ vendor }}</h1>{% endblock %}